---
- name: Example of bpftrace
  hosts: monitoring
  roles:
    - role: performancecopilot.metrics.bpftrace
      vars:
        bpftrace_users:
          - {user: metrics, sasluser: metrics, saslpassword: p4ssw0rd}
