---
- hosts: all
  roles:
    - role: fedora.performancecopilot.pcp
      vars:
        pcp_pmlogger_interval: 10
        pcp_optional_agents: ['dm', 'nfsclient', 'openmetrics']
        pcp_explicit_labels:
          environment: "production"
