---
- name: Example of pcp with users
  hosts: monitoring
  roles:
    - role: performancecopilot.metrics.pcp
      vars:
        pcp_accounts:
          - {user: metrics, sasluser: metrics, saslpassword: p4ssw0rd}
          - {sasluser: nathans, saslpassword: "adm1n!"}
